import React from "react"
import { useNavigate } from "react-router-dom"
import "./ReviewFeedback.css"

function ReviewFeedback() {
  const navigate = useNavigate()

  const handleBackToHome = () => {
    navigate("/")
  }

  return (
    <div className="review-feedback">
      <div className="header">
        <button onClick={handleBackToHome} className="back-button">
          ⬅️
        </button>
        <h1>🍐 educationhome.planet</h1>
      </div>
      
      <div className="page-content">
        <h2>Review Feedback from Previous Sessions</h2>
        <div className="feedback-content">
          <div className="feedback-section">
            <div className="feedback-stats">
              <h3>1. Session Statistics 📊</h3>
              <p>To get started, here are a few baseline statistics about active learning from your most recent session. Increases in these numbers are a great indication that you're improving your learner engagement strategies.</p>
              
              <div className="stat-box" style={{backgroundColor: "#e8f5e9"}}>
                <p><strong>Talk Time Distribution:</strong></p>
                <p>Your learners talked 1% of the time, and you talked 98% of the time.</p>
                <p className="trend-down">↓ This is a 10% decrease in learner talk time from last time.</p>
              </div>

              <div className="stat-box" style={{backgroundColor: "#e8f5e9"}}>
                <p><strong>Learner Engagement:</strong></p>
                <p>5 of your 10 learners engaged at least once.</p>
                <p>Last session, 5 out of 11 learners engaged.</p>
              </div>
            </div>

            <div className="feedback-highlights">
              <h3>2. Session Highlights 👏</h3>
              <p>Following that, here are some auto-selected session highlights when you did a great job bringing out learner ideas.</p>
              
              <div className="highlight-box">
                <p style={{backgroundColor: "#e3f2fd"}}><span className="timestamp">01:15:00</span> You: So what is this point over here with the right angle?</p>
                <p style={{backgroundColor: "#e3f2fd"}}><span className="timestamp">02:13:15</span> You: So Shawn how did you approach this problem?</p>
                <p style={{backgroundColor: "#e3f2fd"}}><span className="timestamp">01:03:03</span> You: What is an exponential function?</p>
              </div>

              <div className="example-box">
                <p><strong>Here's another great example from a fellow SAT bootcamp tutor:</strong></p>
                <p style={{backgroundColor: "#e3f2fd"}}>Tutor: Can you tell me a little more about how you got to the number 348 and why you chose to do it that way?</p>
              </div>
            </div>

            <div className="feedback-personalized">
              <h3>3. Personalized Feedback ❤️</h3>
              <p>Below is some personalized feedback from GPT-4 on your session. This feedback was generated by reviewing your session transcript and looking for opportunities to implement strategies that past SAT tutors have found to be effective.</p>
              
              <div className="feedback-box">
                <p style={{backgroundColor: "#e3f2fd"}}>You provided a detailed explanation of many problems, which is great. However, I noticed a moment when you could have given more space for learners to verbalize their thoughts. For instance, towards the end of the session, you ask Learner8 to go over a particular problem. She admits to not understanding it and you then proceed to explain the problem in great detail yourself. Instead, you might have asked Learner8 what specifically was confusing about the question, or asked her to share her thought process when she approached it. This would have given her the opportunity to articulate and address her struggles with the problem, fostering a "we do" learning environment.</p>
              </div>

              <p className="tip-link">Need a little more inspiration for asking questions in your next session? Please check out our cheat sheet of Tips for Asking Good Questions.</p>
            </div>

            <div className="feedback-conclusion">
              <h3>4. Next Steps 💡</h3>
              <p>That's all! Thanks for reviewing. Considering this feedback, what's one strategy you hope to implement in your next session?</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default ReviewFeedback 